README.md
bank.go
request.go
response.go

here the PR for this issue https://github.com/veritrans/go-midtrans/issues/1

change to use BCABankTransferLangDetail instead BCABankTransferDetail

---

response.go

https://api-docs.midtrans.com/#indomaret

Add payment code following the charge response on midtrans doc

---

request.go

Add mandiri_ecash on charge request for Mandiri eCash

---

LICENSE
README.md
bank.go
client.go
core.go
envtype.go
paysource.go
request.go
response.go
snap.go

Hi @rizdaprasetya and Midtrans team,
Based on issue #11 , I'd like to create pull request to make this library more awesome! 😄 
You can check the Go Report Card difference between my fork repo and this repo before this PR approved in here : 
https://goreportcard.com/report/github.com/haritsfahreza/go-midtrans (fork)
https://goreportcard.com/report/github.com/veritrans/go-midtrans (master)
Also I add Apache 2.0 LICENSE file, regarding into the issue #10 
Please take a look 🙏

Improve Go Report Card and add LICENSE

---

README.md
client_test.go
example/simplepay/main.go

Hi @rizdaprasetya and Midtrans team,
First of all, I'm sorry that I forgot to run the unit test before submit my last PR. I found field `APIEnvType` that I changed because of the recommendation from golint, hasn't been replaced yet in some place. So please take a look at my PR to fix it 🙏 
Thanks,
Harits Fahreza C.

Fix field APIEnvType 

---

client.go

Hi @rizdaprasetya and Midtrans team,
Based on issue #18 , I'd like to create pull request to make add HTTP Status Code into `SnapResponse` and `Response` of Core API 😄
Please take a look 🙏 Thanks!

Set HTTP Status Code into SnapResponse

---

envtype.go
iris.go
response.go

this is my first work on iris, i create simple wrapper to get list beneficiary banks
If this PR approved, i continue to write another iris wrapper
Please take a look @rizdaprasetya , please let me know what do you thought

[iris] get list beneficiary banks

---

README.md
client.go
iris.go
response.go

- create beneficiaries
- update beneficiaries
- get list beneficiaries

[iris] beneficiaries API

---

request.go

Add new parameter enable callback and callback url on charge request with payment type = gopay

add gopay enable callback and callback url on charge request

---

README.md
client.go
core_test.go
paysource.go
paysource_test.go
snap.go
snap_test.go

- Fix logger
- add other_va to paysource
- remove enabled_payments from Snap GetTokenQuick
- add core & snap test
- add more Snap example

Fix logger, add test, fix GetTokenQuick, add other_va

---

request.go

Add parameter authentication on credit card detail struct for support 3d secure

Add authentication parameter credit card detail for support 3d secure

---

response.go

Add masked_card, currency and card_type attribute to response struct

Add masked_card, currency and card_type attribute to response struct

---

request.go
snap_test.go

fix https://github.com/veritrans/go-midtrans/issues/36

add expiry param for snap

---

iris.go
request.go
response.go

Exmple code
```go
irisApproverKey := "IRIS-XXXX"
midclient := midtrans.NewClient()
midclient.ServerKey = irisApproverKey
midclient.APIEnvType = midtrans.Sandbox
midclient.LogLevel = 3
var irisGateway midtrans.IrisGateway
irisGateway = midtrans.IrisGateway{
Client: midclient,
}
otp := ""
var payouts = midtrans.IrisApprovePayoutReq{
ReferenceNo: []string{"2b7f4596aef27645b6", "fabdf547aa5ae116cf"},
OTP:         otp,
}
payoutRes, err := irisGateway.ApprovePayouts(payouts)
fmt.Println("res ApprovePayouts ", payoutRes)
fmt.Println("err ApprovePayouts ", err)
```
success example
```
{ok  []}
```
error example
```
Payouts not found. Please check reference nos
```
```
Reference nos 'd6b2f7604ba899bfd4' are not queued
```
Exmple code
```go
irisApproverKey := "IRIS-XXXX"
midclient := …
```

approve & reject payouts

---

iris.go
response.go

```go
irisApproverKey := "IRIS-XXXX"
midclient := midtrans.NewClient()
midclient.ServerKey = irisApproverKey
midclient.APIEnvType = midtrans.Sandbox
midclient.LogLevel = 3
var irisGateway midtrans.IrisGateway
irisGateway = midtrans.IrisGateway{
Client: midclient,
}
// get payout details
referenceNo := "2b7f4596aef27645b6"
payoutRes, err := irisGateway.GetPayoutDetails(referenceNo)
fmt.Println("res GetPayoutDetails ", payoutRes)
fmt.Println("err GetPayoutDetails ", err)
```
```
res GetPayoutDetails  {100000.0 John Doe 3345278421 PT. BANK CENTRAL ASIA TBK. 2b7f4596aef27645b6 Payout 1 beneficiary@example.com processed Creator 2019-09-12 13:46:03 +0000 UTC 2019-09-19 01:10:11 +0000 UTC  }
```
`referenceNo:= "asdf"`
```
Specified payout not found
```
`referenceNo:= ""`
```
you must specified …
```

get payout details & validate bank account

---

iris.go
response.go

@rizdaprasetya please review
```go
irisApproverKey := "IRIS-XXXX"
midclient := midtrans.NewClient()
midclient.ServerKey = irisApproverKey
midclient.APIEnvType = midtrans.Sandbox
midclient.LogLevel = 3
var irisGateway midtrans.IrisGateway
irisGateway = midtrans.IrisGateway{
Client: midclient,
}
// payout history
startDate := "2019-09-24"
endDate := "2019-09-30"
payoutHistory, err := irisGateway.GetPayoutHistory(startDate, endDate)
fmt.Println("res GetPayoutHistory ", payoutHistory)
fmt.Println("err GetPayoutHistory ", err)
```
```
res GetPayoutHistory [{100000.0 John Doe 3345278421 PT. BANK CENTRAL ASIA TBK. d6b2f7604ba899bfd4 Payout 1 beneficiary@example.com processed Creator 2019-09-12 14:02:31 +0000 UTC 2019-09-19 01:05:29 +0000 UTC  }]
```
```
res GetPayoutHistory []
```
```go …
```

get payout history & check balance

---

client.go

Based on issue #49 , here my pull request to fix it
Please review 🙏 Thanks!

fix condition on fill StatusCode

---

core.go

There are small mistake. It should use POST instead of GET

change refund request to POST

---

core.go
response.go

Refund struct on core gateway

---

core.go
core_test.go
request.go
response.go
subscribe_test.go

Add /v1/subscriptions function

Add Subscription Function

---

core.go
core_test.go
response.go
snap_test.go
subscribe_test.go

adding
- get subscription detail
- enable subscription
- disable subscription
- update subscription

Completing Recurring API

---

request.go

Hi, I would like to fix certain things that I found when I use this repo.
1. a missing code on this struct `InstallmentTermsDetail`
2. on this field `Terms` there is have a different type, `Term` must be an object instead of array of object
https://snap-docs.midtrans.com/#request-body-json-parameter

Fix installment struct

---

response.go

add Transaction IDs field to struct subscription response

---

core.go

add deny transaction method, to fix issue [#65](https://github.com/veritrans/go-midtrans/issues/65)

add deny transaction method

---

request.go

Need to add 2 fields (max_interval & start_time) to ScheduleDetailReq
related to realtime recurring subscription

Update request.go - ScheduleDetailReq struct

---

request.go

I add whitelist_bins as WhitelistBins into CreditCardDetail

Add whitelist_bins into CreditCardDetail

---

request.go

Add missing callbacks field to `SnapReq` structs

Add callbacks field to SnapReq structs

---

paysource.go
paysource_test.go
request.go

Add ShopeePay payment method and ShopeePay Object based on [documentation](https://api-docs.midtrans.com/#shopeepay)

Add ShopeePay payment method
